// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<main.OpenFileRes>;

export function SaveAs(arg1:string):Promise<main.SaveRes>;
